databases-week3
Hailegebriel22/hyf-homework pull request #26
Opened 2022-08-31 11:58 UTC by Hailegebriel22

2022-09-03 13:14 UTC, Hanouj commented on databases/week3/mealSharingDB.sql
> +CREATE TABLE
Great job here Haile you are really good at creating tables and connecting them together

2022-09-03 14:01 UTC, Hanouj reviewed
Great work on the homework Haile keep it up

2022-09-03 14:01 UTC, Hanouj commented on databases/week3/mealSharingQueries.sql
> +        1,
Hi Haile nice work, but here id has an auto incremented primary key then there is an advantage that you do not need to give value for that column in the INSERT command. This means MySQL will give the value for that column

2022-09-03 14:01 UTC, Hanouj commented on databases/week3/mealSharingQueries.sql
> +ORDER BY created_date;
nice work Haile, here just add ORDER BY created_date ASC;
 to sort the result set in ascending order

2022-09-04 10:46 UTC, Elia-Git requested changes
Haile really grear work. Optionally, you can  implement Hanouj's feedback regarding auto increment id(is a good catch) & then ship it.

2022-09-04 18:25 UTC, Hailegebriel22 commented on databases/week3/mealSharingQueries.sql
> +ORDER BY created_date;
Thanks, but the default is ASC.

2022-09-04 21:05 UTC, Elia-Git approved these changes
Ship it pls. Thanks!

2022-10-09 21:41 UTC, merged