react-react1-week1
Hailegebriel22/hyf-homework pull request #30
Opened 2022-09-27 18:22 UTC by Hailegebriel22

2022-09-27 19:35 UTC, Gohar33 requested changes

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Main.jsx
> +import Todolist from "./Todolist"
If you're using two or more words together, then use a Pascal case, all words with capital letters. So your `Todolist` will be `TodoList`

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Main.jsx
> +export default function Main(){
`export default function Main() {` there should be a space between parentheses and an opening curly brace. Correct this everywhere.

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Main.jsx
> +
Don't leave unnecessary empty lines. Not only here but everywhere in your code

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todolist.jsx
> +const todolist =[
here `todolist` should be written with Camel case. It will be `todoList`

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todolist.jsx
> +
You could separately import data. Separation of concerns is essential for React.

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todolist.jsx
> +        <div className="ul">
Not the best className

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todopage.css
> +   ul { text-align:left;
Please, be careful with the syntax also. `text-align:left; ` goes the next line and it should be written with the space before colon `text-align :left;` it concern all your code, not only in CSS

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todopage.jsx
> +import "./Todopage.css"
Again `Todopage.css` should be `TodoPage.css`

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todopage.jsx
> +    )
I don't know why are you not writing `import React from 'react';`? I know it's not necessary but it gives clean look to your react code.

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todolist.jsx
> +        {todolist.map(todo=><TodoListTask todo={todo} key={todo.id} />)}
Component name should go next line. Try to keep a clean syntax.

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todopage.css
> +
here also, why empty line?

2022-09-27 19:35 UTC, Gohar33 commented on react/react1/week1/todo-list/src/Todopage.css
> +padding-left: 12em;
indent code

2022-09-30 12:04 UTC, Hanouj reviewed
Great job in this week hw Haile, I could see you get a lot of good reviews from Gohar, try to implements those

2022-09-30 12:04 UTC, Hanouj commented on react/react1/week1/todo-list/src/Todolist.jsx
> +    return <li> {todo.description},{todo.deadline}</li>
well done here

2022-10-02 17:47 UTC, merged